---
title: "Untitled"
output: html_document
date: "2023-02-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(caret)
library(rpart)
library(scales)

wine = read_rds("pinot.rds")
```

text feature engineering: 
```{r}
wine_words <- function(df, j = 1000, stem=F){ 
  library(tidytext)
  library(SnowballC)
  data(stop_words)

  words <- df %>%
    unnest_tokens(word, description) %>%
    anti_join(stop_words) %>% # get rid of stop words
    filter(!(word %in% c("wine","pinot","vineyard", "price", "points")))
  
  if(stem){
    words <- words %>% 
      mutate(word = wordStem(word))
  }
  
  words <- words %>% 
    count(id, word) %>% 
    group_by(id) %>% 
    mutate(exists = (n>0)) %>% 
    ungroup %>% 
    group_by(word) %>% 
    mutate(total = sum(n)) %>% 
    filter(total > j) %>% 
    pivot_wider(id_cols = id, names_from = word, values_from = exists, values_fill = list(exists=0)) %>% 
    right_join(select(df,id,province)) %>% 
    mutate(across(-province, ~replace_na(.x, F)))
}

wino <- wine_words(wine, j=200, stem=T)

```

bringing back numerical features from original dataset to wino: 
```{r}
wino = wino %>% left_join(select(wine, id, price, points, year), by = "id")
```

Numerical feature engineering: 
```{r}
#center and scale points: 
wino = wino %>% select(points) %>% preProcess(method = c("center", "scale")) %>% predict(wino)

#year as factor, logprice: 
wino = wino %>% mutate(year_f = as.factor(year), 
                         lprice = log(price))


#binning year and and price: 
wino = wino %>% 
  mutate(price_f = case_when(
    price < 16 ~ "low",
    price >= 16 & price < 41 ~ "med",
    price >= 41 ~ "high"
  ), 
   year_f = case_when(
    year < 2005 ~ "old",
    year >= 2005 & year < 2011 ~ "recent",
    year >= 2011 ~ "current"
  ))

wino = wino %>% dplyr::select(-price)

#difference of wine's lprice from total average lprice
wino = wino %>% mutate(diff_from_avg_lprice = mean(lprice) - lprice)


wino = wino %>% mutate(cost_per_point = lprice/points) 

```

initial set up for fitting model: 
```{r}
set.seed(504) 

ctrl <- trainControl(method = "cv", number = 5)

wine_index <- createDataPartition(wino$province, p = 0.80, list = FALSE)
train <- wino[ wine_index, ]
test <- wino[-wine_index, ]
```


weighting
```{r}
total = wine %>% nrow()
province_dist = wine %>% group_by(province) %>% count() %>% mutate(prop = n/total) 


ca_prop = as.numeric(province_dist[2,'prop'])
province_dist = province_dist %>% mutate(rel_to_CA = ca_prop/prop)

weighted_wine = train %>% 
  mutate(weights = case_when(
    province == "Burgundy" ~ as.numeric(province_dist[1,4]),
    province == "California" ~ as.numeric(province_dist[2,4]),
    province == "Casablanca_Valley" ~ as.numeric(province_dist[3,4]),
    province == "Marlborough" ~ as.numeric(province_dist[4,4]),
    province == "New_York" ~ as.numeric(province_dist[5,4]),
    province == "Oregon" ~ as.numeric(province_dist[6,4]),
  ))
```


```{r}
tuneGrid = expand.grid(mtry = seq(10,20,1))

fit <- train(province ~ .,
             data = train, 
             method = "rf",
             tuneGrid = tuneGrid,
             weights = weighted_wine$weights,
             trControl = ctrl,
             metric = "Kappa")

confusionMatrix(predict(fit, test),factor(test$province))

#best tune of mtry = 10
```

